config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/help'
  get 'static_pages/about'
  get 'projects/search', to: 'projects#search', as: 'projects_search'
  get 'projects',to: 'projects#index'

  root 'projects#index'

end

app/models/project.rb
class Project
  # attr_accessible :keywords, :location
  def self.search(search)
       #find(:all, :conditions => ['location LIKE ?',search])
    search = Cb.job.search_criteria.location(params[:search]).radius(10).search()

    search.each do |job|
      puts job.title
      puts job.company_name
      puts job.instance_variables
    end

  else
      find(:all)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
    render text: 'hello world'
  end

end

app/controllers/projects_controller.rb
require 'cb'
Cb.configure do |config|
  config.dev_key    = 'WDHV2ZS6091Z9BQC0R04'
  config.time_out   = 5
end


class ProjectsController < ApplicationController
  def index
  end

  def search
    criteria = {}
    criteria[:Location] = params[:location]
    criteria[:Keywords] = params[:keywords]
    @job_results = Cb.job.search criteria
    #binding.pry #Cannot be the last line of executed code

    #@job_results = search
    #@results = Project.search params[:keywords]
  end

  def getCompanyComments
    Cb::Requests::Company::Find.new()
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all',
                             'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/projects/index.html.haml
%h2{:align => "center"} Job Search
%body
-#%form{:action => "search", :method => "get" ,:controller => "projects"}
= form_tag(projects_search_path, :method => "get", id: "search-form", action: "search") do
  .row
    .column
      Keywords
  .row
    .column
      -#%input{:id => "keywords",:class => "search-field",:type => "text",:align =>"center",:style => "width:100%",:name => "keywords"}
      = text_field_tag :keywords, params[:keywords], class: "search-field", placeholder: "Search Keywords"
  .row
    .column
      Location
  .row
    .column
      -#%input{:id => "location",:class => "search-field",:type => "text",:align =>"center",:style => "width:100%",:name => "location"}
      = text_field_tag :location, params[:location], class: "search-field", placeholder: "Search Location"
  .row
    .column
      %input{:type => "submit",:align =>"center",:style => "width:100%"}

app/views/projects/oldindex.html.haml
%h2{:align => "center"} Job Search
%body
-#%form{:action => "search", :method => "get" ,:controller => "projects"}
= form_tag(projects_search_path, :method => "get", id: "search-form", action: "search") do
  .row
    .column
      Keywords
  .row
    .column
      -#%input{:id => "keywords",:class => "search-field",:type => "text",:align =>"center",:style => "width:100%",:name => "keywords"}
      = text_field_tag :keywords, params[:keywords], class: "search-field", placeholder: "Search Keywords"
  .row
    .column
      Location
  .row
    .column
      -#%input{:id => "location",:class => "search-field",:type => "text",:align =>"center",:style => "width:100%",:name => "location"}
      = text_field_tag :location, params[:location], class: "search-field", placeholder: "Search Location"
  .row
    .column
      %input{:type => "submit",:align =>"center",:style => "width:100%"}

app/views/projects/search.html.erb
<html lang="en">
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>career swipe</title>
    <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" %>
    <%= javascript_include_tag "application" %>
    <script>
        $(document).ready(function() {
            Slider = $('#slider').Swipe({
//                auto: 3000,
//                continuous: true
            }).data('Swipe');

            $('.next').on('click', Slider.next);
            $('.prev').on('click', Slider.prev);
        });
    </script>

    </head>
    <div class="container">
      <div class="navbar-header">
        <a href="/#">
        <button type="button" class="navbar-toggle" data-toggle="collapse"
                data-target="#index">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          </a>
        <a class="navbar-brand" href="/#">career swipe</a>
      </div>
      <!--<div id="navbar" class="navbar-collapse collapse">-->
        <!--<ul class="nav navbar-nav">-->
          <!--<li class="active"><a href="#">Home</a></li>-->
          <!--<li><a href="#about">About</a></li>-->
          <!--<li><a href="#contact">Contact</a></li>-->
        <!--</ul>-->
      <!--</div>-->
    </div>

<body>
<br/>
<div id = "global-container">
    <div class="demo-wrapper">
        <div id="slider" class="swipe" style="visibility: visible;">
            <div class="swipe-wrap" style="width: 3000px; background-color: #0079B5">
                <% (@job_results).models.jobs.each do |job| %>
                <div data-index="0" style="width: 600px; left: 0px; transition-duration: 300ms; -webkit-transition-duration: 300ms; -webkit-transform: translate(-600px, 0px) translateZ(0px);">
                  <p><img src="http://c.tadst.com/gfx/600x400/international-programmer-day.jpg?1" alt="Smiley face" align="middle" style='width:100%;' border="0"> </p>
                  <div id="jobdetails" class="container">
                    <label>Location: <%= job.location %></label><br/>
                    <label>Type: <%= job.title %></label><br/>
                    <label>Salary:</label><br/>
                    <label>Company: <%= job.company_name %></label><br/>
                    <label>Details:</label><br/>
                </div>
                </div>
                <% end %>
            </div>
            <!--<span class="nav prev">Prev</span>-->
            <!--<span class="nav next">Next</span>-->

        </div>
      </div>
</div>


</body>

<footer>

</footer>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
    book</a>.
</p>

app/views/static_pages/home.html.erb
<h1>Sample App</h1>
<p>
  This is the home page for the
  <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>